CMSDashboard: cms.dashboard.ui.TaskViewActivity Class Reference
cms.dashboard.ui.TaskViewActivity Class Reference
Classes
class loadTasks
Public Member Functions
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Package Attributes
ArrayList< HashMap< String,
String > > tasklist = new ArrayList<HashMap<String,String>>()
Private Member Functions
void getTasks ()
String createJsonURL (String _gridName, String _timeRange)
Private Attributes
String GRID_NAME = ""
String TIME_RANGE = ""
ProgressDialog progressDialog
loadTasks loadTasksAsync
Detailed Description
Definition at line 34 of file TaskViewActivity.java.
Member Function Documentation
String cms.dashboard.ui.TaskViewActivity.createJsonURL (String _gridName, String _timeRange) [private]
Definition at line 227 of file TaskViewActivity.java.
Referenced by cms.dashboard.ui.TaskViewActivity.loadTasks.doInBackground().
void cms.dashboard.ui.TaskViewActivity.getTasks () [private]
Definition at line 85 of file TaskViewActivity.java.
References cms.dashboard.ui.TaskViewActivity.loadTasksAsync, and cms.dashboard.ui.TaskViewActivity.progressDialog.
Referenced by cms.dashboard.ui.TaskViewActivity.onCreate(), and cms.dashboard.ui.TaskViewActivity.onOptionsItemSelected().
void cms.dashboard.ui.TaskViewActivity.onCreate (Bundle savedInstanceState) [protected]
Definition at line 43 of file TaskViewActivity.java.
References cms.dashboard.ui.TaskViewActivity.getTasks(), cms.dashboard.ui.TaskViewActivity.GRID_NAME, and cms.dashboard.ui.TaskViewActivity.TIME_RANGE.
boolean cms.dashboard.ui.TaskViewActivity.onCreateOptionsMenu (Menu menu)
Definition at line 62 of file TaskViewActivity.java.
boolean cms.dashboard.ui.TaskViewActivity.onOptionsItemSelected (MenuItem item)
Definition at line 69 of file TaskViewActivity.java.
References cms.dashboard.ui.TaskViewActivity.getTasks().
Member Data Documentation
String cms.dashboard.ui.TaskViewActivity.GRID_NAME = "" [private]
Definition at line 36 of file TaskViewActivity.java.
Referenced by cms.dashboard.ui.TaskViewActivity.loadTasks.doInBackground(), and cms.dashboard.ui.TaskViewActivity.onCreate().
loadTasks cms.dashboard.ui.TaskViewActivity.loadTasksAsync [private]
Definition at line 40 of file TaskViewActivity.java.
Referenced by cms.dashboard.ui.TaskViewActivity.getTasks().
ProgressDialog cms.dashboard.ui.TaskViewActivity.progressDialog [private]
Definition at line 38 of file TaskViewActivity.java.
Referenced by cms.dashboard.ui.TaskViewActivity.getTasks(), and cms.dashboard.ui.TaskViewActivity.loadTasks.onPostExecute().
ArrayList<HashMap<String,String> > cms.dashboard.ui.TaskViewActivity.tasklist = new ArrayList<HashMap<String,String>>() [package]
Definition at line 39 of file TaskViewActivity.java.
Referenced by cms.dashboard.ui.TaskViewActivity.loadTasks.doInBackground(), and cms.dashboard.ui.TaskViewActivity.loadTasks.onPostExecute().
String cms.dashboard.ui.TaskViewActivity.TIME_RANGE = "" [private]
Definition at line 37 of file TaskViewActivity.java.
Referenced by cms.dashboard.ui.TaskViewActivity.loadTasks.doInBackground(), and cms.dashboard.ui.TaskViewActivity.onCreate().
The documentation for this class was generated from the following file:
F:/Development/Workplace/CMS Dashboard/src/cms/dashboard/ui/TaskViewActivity.java