CMSDashboard: cms.dashboard.ui.TaskViewActivity.loadTasks Class Reference
cms.dashboard.ui.TaskViewActivity.loadTasks Class Reference
Public Member Functions
String getElapsedTime (String dt)
Protected Member Functions
JSONObject doInBackground (Void...params)
void onPostExecute (JSONObject json)
void onCancelled ()
Detailed Description
Definition at line 106 of file TaskViewActivity.java.
Member Function Documentation
JSONObject cms.dashboard.ui.TaskViewActivity.loadTasks.doInBackground (Void... params) [protected]
Definition at line 109 of file TaskViewActivity.java.
References cms.dashboard.ui.TaskViewActivity.createJsonURL(), cms.dashboard.ui.TaskViewActivity.loadTasks.getElapsedTime(), cms.dashboard.ui.JSONFunctions.getJSONFromURL(), cms.dashboard.ui.TaskViewActivity.GRID_NAME, cms.dashboard.ui.TaskViewActivity.tasklist, and cms.dashboard.ui.TaskViewActivity.TIME_RANGE.
String cms.dashboard.ui.TaskViewActivity.loadTasks.getElapsedTime (String dt)
Definition at line 140 of file TaskViewActivity.java.
Referenced by cms.dashboard.ui.TaskViewActivity.loadTasks.doInBackground().
void cms.dashboard.ui.TaskViewActivity.loadTasks.onCancelled () [protected]
Definition at line 219 of file TaskViewActivity.java.
void cms.dashboard.ui.TaskViewActivity.loadTasks.onPostExecute (JSONObject json) [protected]
Definition at line 165 of file TaskViewActivity.java.
References cms.dashboard.ui.TaskViewActivity.progressDialog, and cms.dashboard.ui.TaskViewActivity.tasklist.
The documentation for this class was generated from the following file:
F:/Development/Workplace/CMS Dashboard/src/cms/dashboard/ui/TaskViewActivity.java