CMSDashboard: cms.dashboard.ui.CMSDashboardActivity Class Reference
cms.dashboard.ui.CMSDashboardActivity Class Reference
Public Member Functions
void onCreate (Bundle savedInstanceState)
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
void rememberName (View v)
void selectGridNm (View v)
void loadTasks (View v)
Protected Member Functions
void onActivityResult (int requestCode, int resultCode, Intent data)
Package Attributes
String timeRange
Boolean bTimeRange
Private Member Functions
void loadPreference ()
void savePrefGridName ()
void removePrefGridName ()
void loadTimeRange ()
Private Attributes
String gridName
Boolean bGridNm
Static Private Attributes
static final int CHOOSE_GRIDNAME = 0
Detailed Description
Definition at line 20 of file CMSDashboardActivity.java.
Member Function Documentation
void cms.dashboard.ui.CMSDashboardActivity.loadPreference () [private]
Definition at line 64 of file CMSDashboardActivity.java.
References cms.dashboard.ui.CMSDashboardActivity.bGridNm, cms.dashboard.ui.CMSDashboardActivity.gridName, cms.dashboard.ui.PreferenceConnector.Name, cms.dashboard.ui.PreferenceConnector.readBoolean(), cms.dashboard.ui.PreferenceConnector.readString(), and cms.dashboard.ui.PreferenceConnector.Saved_Name.
Referenced by cms.dashboard.ui.CMSDashboardActivity.onCreate().
void cms.dashboard.ui.CMSDashboardActivity.loadTasks (View v)
Definition at line 193 of file CMSDashboardActivity.java.
References cms.dashboard.ui.CMSDashboardActivity.bGridNm, cms.dashboard.ui.CMSDashboardActivity.bTimeRange, cms.dashboard.ui.CMSDashboardActivity.gridName, and cms.dashboard.ui.CMSDashboardActivity.timeRange.
void cms.dashboard.ui.CMSDashboardActivity.loadTimeRange () [private]
Definition at line 106 of file CMSDashboardActivity.java.
References cms.dashboard.ui.CMSDashboardActivity.bTimeRange, and cms.dashboard.ui.CMSDashboardActivity.timeRange.
Referenced by cms.dashboard.ui.CMSDashboardActivity.onCreate().
void cms.dashboard.ui.CMSDashboardActivity.onActivityResult (int requestCode, int resultCode, Intent data) [protected]
Definition at line 169 of file CMSDashboardActivity.java.
References cms.dashboard.ui.CMSDashboardActivity.bGridNm, cms.dashboard.ui.CMSDashboardActivity.CHOOSE_GRIDNAME, cms.dashboard.ui.CMSDashboardActivity.gridName, and cms.dashboard.ui.CMSDashboardActivity.savePrefGridName().
void cms.dashboard.ui.CMSDashboardActivity.onCreate (Bundle savedInstanceState)
Called when the activity is first created.
Definition at line 28 of file CMSDashboardActivity.java.
References cms.dashboard.ui.CMSDashboardActivity.bGridNm, cms.dashboard.ui.CMSDashboardActivity.bTimeRange, cms.dashboard.ui.CMSDashboardActivity.loadPreference(), and cms.dashboard.ui.CMSDashboardActivity.loadTimeRange().
boolean cms.dashboard.ui.CMSDashboardActivity.onCreateOptionsMenu (Menu menu)
Definition at line 40 of file CMSDashboardActivity.java.
boolean cms.dashboard.ui.CMSDashboardActivity.onOptionsItemSelected (MenuItem item)
Definition at line 52 of file CMSDashboardActivity.java.
void cms.dashboard.ui.CMSDashboardActivity.rememberName (View v)
Definition at line 99 of file CMSDashboardActivity.java.
References cms.dashboard.ui.CMSDashboardActivity.bGridNm, cms.dashboard.ui.CMSDashboardActivity.removePrefGridName(), and cms.dashboard.ui.CMSDashboardActivity.savePrefGridName().
void cms.dashboard.ui.CMSDashboardActivity.removePrefGridName () [private]
Definition at line 91 of file CMSDashboardActivity.java.
References cms.dashboard.ui.PreferenceConnector.getEditor(), cms.dashboard.ui.PreferenceConnector.Name, and cms.dashboard.ui.PreferenceConnector.Saved_Name.
Referenced by cms.dashboard.ui.CMSDashboardActivity.rememberName().
void cms.dashboard.ui.CMSDashboardActivity.savePrefGridName () [private]
Definition at line 80 of file CMSDashboardActivity.java.
References cms.dashboard.ui.CMSDashboardActivity.bGridNm, cms.dashboard.ui.CMSDashboardActivity.gridName, cms.dashboard.ui.PreferenceConnector.Name, cms.dashboard.ui.PreferenceConnector.Saved_Name, cms.dashboard.ui.PreferenceConnector.writeBoolean(), and cms.dashboard.ui.PreferenceConnector.writeString().
Referenced by cms.dashboard.ui.CMSDashboardActivity.onActivityResult(), and cms.dashboard.ui.CMSDashboardActivity.rememberName().
void cms.dashboard.ui.CMSDashboardActivity.selectGridNm (View v)
Definition at line 160 of file CMSDashboardActivity.java.
References cms.dashboard.ui.CMSDashboardActivity.CHOOSE_GRIDNAME.
Member Data Documentation
Boolean cms.dashboard.ui.CMSDashboardActivity.bGridNm [private]
Definition at line 23 of file CMSDashboardActivity.java.
Referenced by cms.dashboard.ui.CMSDashboardActivity.loadPreference(), cms.dashboard.ui.CMSDashboardActivity.loadTasks(), cms.dashboard.ui.CMSDashboardActivity.onActivityResult(), cms.dashboard.ui.CMSDashboardActivity.onCreate(), cms.dashboard.ui.CMSDashboardActivity.rememberName(), and cms.dashboard.ui.CMSDashboardActivity.savePrefGridName().
Boolean cms.dashboard.ui.CMSDashboardActivity.bTimeRange [package]
Definition at line 23 of file CMSDashboardActivity.java.
Referenced by cms.dashboard.ui.CMSDashboardActivity.loadTasks(), cms.dashboard.ui.CMSDashboardActivity.loadTimeRange(), and cms.dashboard.ui.CMSDashboardActivity.onCreate().
final int cms.dashboard.ui.CMSDashboardActivity.CHOOSE_GRIDNAME = 0 [static, private]
Definition at line 24 of file CMSDashboardActivity.java.
Referenced by cms.dashboard.ui.CMSDashboardActivity.onActivityResult(), and cms.dashboard.ui.CMSDashboardActivity.selectGridNm().
String cms.dashboard.ui.CMSDashboardActivity.gridName [private]
Definition at line 22 of file CMSDashboardActivity.java.
Referenced by cms.dashboard.ui.CMSDashboardActivity.loadPreference(), cms.dashboard.ui.CMSDashboardActivity.loadTasks(), cms.dashboard.ui.CMSDashboardActivity.onActivityResult(), and cms.dashboard.ui.CMSDashboardActivity.savePrefGridName().
String cms.dashboard.ui.CMSDashboardActivity.timeRange [package]
Definition at line 22 of file CMSDashboardActivity.java.
Referenced by cms.dashboard.ui.CMSDashboardActivity.loadTasks(), and cms.dashboard.ui.CMSDashboardActivity.loadTimeRange().
The documentation for this class was generated from the following file:
F:/Development/Workplace/CMS Dashboard/src/cms/dashboard/ui/CMSDashboardActivity.java