CMSDashboard: cms.dashboard.ui.PreferenceConnector Class Reference
cms.dashboard.ui.PreferenceConnector Class Reference
Static Public Member Functions
static SharedPreferences getPreferences (Context context)
static Editor getEditor (Context context)
static void writeBoolean (Context context, String key, boolean value)
static boolean readBoolean (Context context, String key, boolean defValue)
static void writeString (Context context, String key, String value)
static String readString (Context context, String key, String defValue)
Static Public Attributes
static final String PREF_NAME = "APP_PREF"
static final int MODE = Context.MODE_PRIVATE
static final String Name = ""
static final String Saved_Name = "savedGridNm"
Detailed Description
Author:
Parth Patel [parthpatel32@gmail.com]
Definition at line 12 of file PreferenceConnector.java.
Member Function Documentation
static Editor cms.dashboard.ui.PreferenceConnector.getEditor (Context context) [static]
Definition at line 24 of file PreferenceConnector.java.
References cms.dashboard.ui.PreferenceConnector.getPreferences().
Referenced by cms.dashboard.ui.CMSDashboardActivity.removePrefGridName(), cms.dashboard.ui.PreferenceConnector.writeBoolean(), and cms.dashboard.ui.PreferenceConnector.writeString().
static SharedPreferences cms.dashboard.ui.PreferenceConnector.getPreferences (Context context) [static]
Definition at line 20 of file PreferenceConnector.java.
References cms.dashboard.ui.PreferenceConnector.MODE, and cms.dashboard.ui.PreferenceConnector.PREF_NAME.
Referenced by cms.dashboard.ui.PreferenceConnector.getEditor(), cms.dashboard.ui.PreferenceConnector.readBoolean(), and cms.dashboard.ui.PreferenceConnector.readString().
static boolean cms.dashboard.ui.PreferenceConnector.readBoolean (Context context, String key, boolean defValue) [static]
Definition at line 33 of file PreferenceConnector.java.
References cms.dashboard.ui.PreferenceConnector.getPreferences().
Referenced by cms.dashboard.ui.CMSDashboardActivity.loadPreference().
static String cms.dashboard.ui.PreferenceConnector.readString (Context context, String key, String defValue) [static]
Definition at line 42 of file PreferenceConnector.java.
References cms.dashboard.ui.PreferenceConnector.getPreferences().
Referenced by cms.dashboard.ui.CMSDashboardActivity.loadPreference().
static void cms.dashboard.ui.PreferenceConnector.writeBoolean (Context context, String key, boolean value) [static]
Definition at line 28 of file PreferenceConnector.java.
References cms.dashboard.ui.PreferenceConnector.getEditor().
Referenced by cms.dashboard.ui.CMSDashboardActivity.savePrefGridName().
static void cms.dashboard.ui.PreferenceConnector.writeString (Context context, String key, String value) [static]
Definition at line 37 of file PreferenceConnector.java.
References cms.dashboard.ui.PreferenceConnector.getEditor().
Referenced by cms.dashboard.ui.CMSDashboardActivity.savePrefGridName().
Member Data Documentation
final int cms.dashboard.ui.PreferenceConnector.MODE = Context.MODE_PRIVATE [static]
Definition at line 14 of file PreferenceConnector.java.
Referenced by cms.dashboard.ui.PreferenceConnector.getPreferences().
final String cms.dashboard.ui.PreferenceConnector.Name = "" [static]
Definition at line 17 of file PreferenceConnector.java.
Referenced by cms.dashboard.ui.CMSDashboardActivity.loadPreference(), cms.dashboard.ui.CMSDashboardActivity.removePrefGridName(), and cms.dashboard.ui.CMSDashboardActivity.savePrefGridName().
final String cms.dashboard.ui.PreferenceConnector.PREF_NAME = "APP_PREF" [static]
Definition at line 13 of file PreferenceConnector.java.
Referenced by cms.dashboard.ui.PreferenceConnector.getPreferences().
final String cms.dashboard.ui.PreferenceConnector.Saved_Name = "savedGridNm" [static]
Definition at line 18 of file PreferenceConnector.java.
Referenced by cms.dashboard.ui.CMSDashboardActivity.loadPreference(), cms.dashboard.ui.CMSDashboardActivity.removePrefGridName(), and cms.dashboard.ui.CMSDashboardActivity.savePrefGridName().
The documentation for this class was generated from the following file:
F:/Development/Workplace/CMS Dashboard/src/cms/dashboard/ui/PreferenceConnector.java